In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## working with Dates

In [7]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### 1. Extract year

In [10]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

#### 2. Extract month

In [13]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [16]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October
3,2019-08-17,7292,25,1,2019,8,17,August
4,2019-01-06,4344,25,3,2019,1,6,January

#### 3. Extract day

In [17]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October
3,2019-08-17,7292,25,1,2019,8,17,August
4,2019-01-06,4344,25,3,2019,1,6,January

In [21]:
#  day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1
3,2019-08-17,7292,25,1,2019,8,17,August,5
4,2019-01-06,4344,25,3,2019,1,6,January,6

In [22]:
#  day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday

In [25]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,December,1,Tuesday,0
1,2018-08-15,2018,8,15,August,2,Wednesday,0
2,2018-10-23,2018,10,23,October,1,Tuesday,0
3,2019-08-17,2019,8,17,August,5,Saturday,1
4,2019-01-06,2019,1,6,January,6,Sunday,1

#### Extract Quarter

In [30]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,December,1,Tuesday,0,4,4
1,2018-08-15,2018,8,15,August,2,Wednesday,0,3,3
2,2018-10-23,2018,10,23,October,1,Tuesday,0,4,4
3,2019-08-17,2019,8,17,August,5,Saturday,1,3,3
4,2019-01-06,2019,1,6,January,6,Sunday,1,1,1

#### Extract Semester

In [32]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,December,1,Tuesday,0,4,4,2
1,2018-08-15,2018,8,15,August,2,Wednesday,0,3,3,2
2,2018-10-23,2018,10,23,October,1,Tuesday,0,4,4,2
3,2019-08-17,2019,8,17,August,5,Saturday,1,3,3,2
4,2019-01-06,2019,1,6,January,6,Sunday,1,1,1,1

#### Extract Time elaspsed between dates

In [34]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 22, 15, 7, 17, 489181)

In [35]:
today - date['date']

0     2416 days 15:07:17.489181
1     2898 days 15:07:17.489181
2     2829 days 15:07:17.489181
3     2531 days 15:07:17.489181
4     2754 days 15:07:17.489181
                 ...
995   2844 days 15:07:17.489181
996   2785 days 15:07:17.489181
997   2633 days 15:07:17.489181
998   2698 days 15:07:17.489181
999   2472 days 15:07:17.489181
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
# months passed

np.round((today - date['date']).dt.days / 30.44, 0)

0      79.0
1      95.0
2      93.0
3      83.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    89.0
999    81.0
Name: date, Length: 1000, dtype: float64

In [38]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [40]:
time['date'] = pd.to_datetime(time['date'])

In [41]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
time['hours']  = time['date'].dt.hour
time['minutes']  = time['date'].dt.minute
time['seconds']  = time['date'].dt.second
time.head()

,date,msg,hour,hours,minutes,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,23,11,0

#### Extract time part

In [45]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,hours,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,23,11,0,23:11:00

#### Time difference

In [46]:
today-time['date']

0     4602 days 14:17:17.489181
1     4466 days 15:27:17.489181
2     4952 days 14:46:17.489181
3     4254 days 14:36:17.489181
4     4651 days 15:56:17.489181
                 ...
995   5241 days 14:17:17.489181
996   4562 days 15:53:17.489181
997   5027 days 15:30:17.489181
998   5143 days 15:33:17.489181
999   4415 days 15:42:17.489181
Name: date, Length: 1000, dtype: timedelta64[ns]